RDKCMF-8696 Dunfell changes causes xupnp build errors
Fix build errors caused by xupnp/46561
../../../../../../../../rdk/components/generic/xupnp/src/xcal-device.c:1956:5: error: 'pnpContext' undeclared (first use in this function)
     pnpContext = gupnp_context_new (NULL, devConf->bcastIf, devConf->bcastPort, &error);
     ^~~~~~~~~~

Change-Id: Id08d6c1a20ac0109cbd4003fd61efe66abe4e626