RDKCOM-1721 RDKCMF-8696 Dunfell changes causes xupnp build errors
Fix build errors caused by xupnp/46561
../../../../../../../../rdk/components/generic/xupnp/src/xcal-device.c:1956:5: error: 'pnpContext' undeclared (first use in this function)
     pnpContext = gupnp_context_new (NULL, devConf->bcastIf, devConf->bcastPort, &error);
     ^~~~~~~~~~

Reason for change: RDKCMF-8696 Dunfell changes causes xupnp build errors
Test Procedure: None.
Risks: Low.
Signed-off-by: Stephen Barrett <stephen.barrett@accenture.com>
Change-Id: Ib9c536ed611ef53da803d11e6ddb6df0049f4165